Section "ServerFlags"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "Sunxi Display"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card0"
EndSection

Section "Monitor"
    Identifier "HDMI Monitor"
EndSection

Section "Screen"
    Identifier "Sunxi Screen"
    Device "Sunxi Display"
    Monitor "HDMI Monitor"
    DefaultDepth 24
EndSection

Section "ServerLayout"
    Identifier "Sunxi Layout"
    Screen 0 "Sunxi Screen"
EndSection

