#!/usr/bin/env python3
"""Compare a board NPU output tensor against an ACUITY host golden tensor.

Purpose: semantic correctness check for NPU golden tests where the golden
was produced by a separate ACUITY host (CPU) quantized inference run rather
than the exact quantization run that produced the NBG under test. vpm_run's
built-in [golden] check is a raw byte memcmp(); that only works when the
golden was produced by the identical quantization run (as with the existing
custom_lut candidate). For lenet/yolov5/resnet50 goldens generated by
scripts/generate-npu-golden.sh, use this instead: it reports top-K index
match plus max/mean absolute difference, RMSE, and cosine similarity between
the two tensors, so a numerically-close-but-not-byte-identical result can
still be judged a pass.

Both inputs are plain text files with one float per (optionally
"index: value") line or whitespace-separated floats per line, matching the
format vpm_run writes with --save_txt 1 and the format
scripts/host/package_acuity_nbg.py (in wuclark/a733_npu_driver) writes for
its host_output_N.txt files.
"""
from __future__ import annotations

import argparse
import math
import re
import sys
from pathlib import Path

FLOAT_RE = re.compile(r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?")


def load_values(path: Path) -> list[float]:
    values: list[float] = []
    with path.open("r", encoding="ascii", errors="ignore") as handle:
        for line in handle:
            if ":" in line:
                line = line.split(":", 1)[1]
            values.extend(float(match.group(0)) for match in FLOAT_RE.finditer(line))
    if not values:
        raise SystemExit(f"no numeric values found in {path}")
    return values


def top_indices(values: list[float], k: int) -> list[int]:
    limit = min(k, len(values))
    return sorted(range(len(values)), key=lambda i: values[i], reverse=True)[:limit]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("golden", type=Path, help="ACUITY host golden tensor text file")
    parser.add_argument("board", type=Path, help="board output tensor text file (vpm_run --save_txt 1)")
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--max-abs-diff", type=float, default=None,
                         help="optional pass/fail threshold for max absolute difference")
    parser.add_argument("--min-cosine", type=float, default=None,
                         help="optional pass/fail threshold for cosine similarity")
    parser.add_argument("--require-top-match", action="store_true",
                         help="fail (exit 1) unless the top-K index sets match")
    args = parser.parse_args()

    golden = load_values(args.golden)
    board = load_values(args.board)
    if len(golden) != len(board):
        raise SystemExit(f"length mismatch: golden={len(golden)} board={len(board)}")

    diffs = [abs(g - b) for g, b in zip(golden, board)]
    max_abs = max(diffs)
    mean_abs = sum(diffs) / len(diffs)
    rmse = math.sqrt(sum(d * d for d in diffs) / len(diffs))
    dot = sum(g * b for g, b in zip(golden, board))
    norm_g = math.sqrt(sum(g * g for g in golden))
    norm_b = math.sqrt(sum(b * b for b in board))
    cosine = dot / (norm_g * norm_b) if norm_g and norm_b else float("nan")

    golden_top = top_indices(golden, args.top_k)
    board_top = top_indices(board, args.top_k)
    top_match = set(golden_top) == set(board_top)

    print(f"length: {len(golden)}")
    print(f"top-{len(golden_top)} index match: {'yes' if top_match else 'no'}")
    print(f"golden top-{len(golden_top)}: {golden_top}")
    print(f"board top-{len(board_top)}: {board_top}")
    print(f"max abs diff: {max_abs:.9f}")
    print(f"mean abs diff: {mean_abs:.9f}")
    print(f"rmse: {rmse:.9f}")
    print(f"cosine: {cosine:.9f}")

    ok = True
    if args.require_top_match and not top_match:
        ok = False
    if args.max_abs_diff is not None and max_abs > args.max_abs_diff:
        ok = False
    if args.min_cosine is not None and (math.isnan(cosine) or cosine < args.min_cosine):
        ok = False
    print(f"result: {'pass' if ok else 'fail'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
