#!/usr/bin/env bash
# Purpose: Create a GitHub Release and publish generated VPU fixture files individually.
# Platform: Host workstation with GitHub CLI authentication and repository release permissions.
# Inputs: Required --tag, optional --target, and exactly 17 generated MP4/framemd5 files.
# Dependencies: Bash, gh, sha256sum, generated testdata/videos, and network access to GitHub.
# Writes: testdata/videos/SHA256SUMS and a remote GitHub Release with uploaded fixture assets.
# Safety: This is an explicit external publishing operation; review generated files and tag before running.
# Repeat: A tag/release is not safely repeatable unless GitHub accepts the requested release operation.
# Recovery: Delete or replace the remote release/assets through GitHub administration; local checksum is disposable.
# Outputs: Release creation/upload diagnostics and SHA256SUMS for published assets.
# Verification: Fetch the pinned release and verify SHA256SUMS before board use.
# Documentation: docs/optional/vpu.md
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
VIDEO_DIR="$REPO_ROOT/testdata/videos"
TAG=""
TARGET=main

usage() {
    cat <<'EOF'
Usage: ./scripts/publish-vpu-test-videos.sh --tag TAG [--target BRANCH]

Create a GitHub Release and upload generated videos individually.
Requires gh authentication and generated files in testdata/videos/.
EOF
}

while (($#)); do
    case "$1" in
        --tag) TAG=${2:?missing tag after --tag}; shift 2 ;;
        --target) TARGET=${2:?missing branch after --target}; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "ERROR: unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
done
[[ -n $TAG ]] || { echo 'ERROR: --tag is required' >&2; exit 2; }
command -v gh >/dev/null 2>&1 || {
    echo 'ERROR: GitHub CLI is required. Install it and run: gh auth login' >&2
    exit 1
}
command -v sha256sum >/dev/null 2>&1 || {
    echo 'ERROR: sha256sum is required. Install coreutils.' >&2
    exit 1
}

mapfile -t MP4S < <(find "$VIDEO_DIR" -maxdepth 1 -type f -name '*.mp4' -printf '%f\n' | sort)
mapfile -t MD5S < <(find "$VIDEO_DIR" -maxdepth 1 -type f -name '*.md5' -printf '%f\n' | sort)
(( ${#MP4S[@]} == 17 )) || { echo 'ERROR: expected 17 MP4 files; run gen_test_videos.sh first' >&2; exit 1; }
(( ${#MD5S[@]} == 17 )) || { echo 'ERROR: expected 17 framemd5 files; run gen_test_videos.sh first' >&2; exit 1; }

(cd "$VIDEO_DIR" && sha256sum -- *.mp4 *.md5 > SHA256SUMS)
gh release create "$TAG" --target "$TARGET" \
    --title "VPU synthetic test videos $TAG" \
    --notes "Synthetic FFmpeg VPU fixtures generated by scripts/gen_test_videos.sh. Files are uploaded individually for direct programmatic access." \
    "$VIDEO_DIR"/*.mp4 "$VIDEO_DIR"/*.md5 "$VIDEO_DIR/SHA256SUMS"
